### ISSUE TITLE
Unable to install modheader.xpi on firefox (v. 57) selenium(v. 3.14)

### ISSUE THREAD

**Issue by AmanpreetAnand** [hao1300/modheader_selenium#1]
Hi,

Getting following error while using the modheader.xpi provided at path modheader_selenium/modheader.xpi
1548960470996	addons.xpi	WARN	Add-on {75145e4e-c014-4625-94db-6dbf92f2f6bb} is not correctly signed.
1548960470996	addons.xpi	WARN	Add-on {75145e4e-c014-4625-94db-6dbf92f2f6bb} is not correctly signed.
1548960470997	addons.xpi	WARN	Add-on {75145e4e-c014-4625-94db-6dbf92f2f6bb} is not correctly signed.

Also tried to use the Firefox Addon with 2.25 version, getting following stacktrace
1548961004034	addons.xpi-utils	WARN	addMetadata: Add-on ModHeader@2.2.5 is invalid: Error: Invalid addon ID: expected addon ID ModHeader@2.2.5, found {ed630365-1261-4ba9-a676-99963d2b4f54} in manifest (resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js:1235:15) JS Stack trace: addMetadata@XPIProviderUtils.js:1235:15 < processFileChanges@XPIProviderUtils.js:1578:23 < checkForChanges@XPIProvider.jsm:3265:34 < startup@XPIProvider.jsm:2182:25 < callProvider@AddonManager.jsm:263:12 < _startProvider@AddonManager.jsm:730:5 < startup@AddonManager.jsm:897:9 < startup@AddonManager.jsm:3081:5 < observe@addonManager.js:65:9

Can you please add the application id and get it signed as well.
  "applications": {
    "gecko": {
      "id": "{ed630365-1261-4ba9-a676-99963d2b4f54}"
    }
  }

**Comment by hao1300** [comment]
Fixed.
