### ISSUE TITLE
how to modify header?

### ISSUE THREAD

**Issue by mhndm** [hao1300/modheader_selenium#2]
please give me an example to modiy header like refere or user agent

**Comment by yunmingwei** [comment]
I want to add some information, such as "test1 = 111 & 2222", which contains "&", so what should I do? i tried to modify the background.js, but it didn't useful

**Comment by hao1300** [comment]
You can take a look at https://github.com/hao1300/modheader_selenium/blob/master/index.js#L22.

Basically you just need to visit a URL like: http://mod-header.appspot.com/add?<header_name>=<header_value> to add a request header.
