### ISSUE TITLE
It looks like ModHeader is serving hard-coded ads without user knowledge

### ISSUE THREAD

**Issue by Giftia** [hao1300/modheader_selenium#48]
![image](https://github.com/modheader/modheader_selenium/assets/12429652/5d1444f9-966a-4dca-9e36-574ebf495dd7)

Such advertisements should clearly indicate that the advertisement comes from ModHeader, rather than an unexpected div suddenly appearing on any web page after a plug-in update one day. This operation is theoretically illegal.

**Comment by Giftia** [comment]
OK，I find this https://modheader.com/articles/ad-supported-plan

**Comment by anthonybaldwin** [comment]
> OK，I find this https://modheader.com/articles/ad-supported-plan

Yikes. They do state that ads are not embedded on pages...

>We will NOT inject ads into other web pages, collect your data, require payment or sign-in for this plan.

But this definitely seems to be triggered w/ _only_ modheader enabled: https://youtu.be/I78kZmJQmQU

If you need the Selenium variant, check out the README in this repo. The original modheader repo was taken down and only this [Selenium] repo w/ links to external sources remains. 😞

Personally, I'll be cancelling my paid subscription and looking for alternative solutions across the board. There are too many unknowns here... Godspeed reading [this](https://robwu.nl/crxviewer/?crx=https%3A%2F%2Fchrome.google.com%2Fwebstore%2Fdetail%2Fmodheader-modify-http-hea%2Fidgpnmonknjnojddfkpgkljpfnnfcklj) obfuscated mess.

Edit: Upon removing the extension (so not just some random embedded ad): https://www.maxai.me/partners/uninstalled/modheader

**Comment by Giftia** [comment]
> > OK，I find this https://modheader.com/articles/ad-supported-plan
> 
> Yikes. They do state that ads are not embedded on pages...
> 
> > We will NOT inject ads into other web pages, collect your data, require payment or sign-in for this plan.
> 
> But this definitely seems to be triggered w/ _only_ modheader enabled: https://youtu.be/I78kZmJQmQU
> 
> If you need the Selenium variant, check out the README in this repo. The original modheader repo was taken down and only this [Selenium] repo w/ links to external sources remains. 😞
> 
> Personally, I'll be cancelling my paid subscription and looking for alternative solutions across the board. There are too many unknowns here... Godspeed reading [this](https://robwu.nl/crxviewer/?crx=https%3A%2F%2Fchrome.google.com%2Fwebstore%2Fdetail%2Fmodheader-modify-http-hea%2Fidgpnmonknjnojddfkpgkljpfnnfcklj) obfuscated mess.
> 
> Edit: Upon removing the extension (so not just some random embedded ad): https://www.maxai.me/partners/uninstalled/modheader

Thanks @anthonybaldwin, very clearly explained.
