### ISSUE TITLE
How to Add Request and Response Headers in ModHeaders for selenium

### ISSUE THREAD

**Issue by iamgowthaman** [hao1300/modheader_selenium#52]
i need add Request Headers and Response Headers in selenium how to add that in my chrome driver.

in Modheaders docs i can see this code to install the extensions. now how to add the headers. 

Selenium code in docs

https://modheader.com/docs/advanced/selenium-webdriver
Java Selenium

For Chrome
```

Path currentRelativePath = Paths.get("chrome-modheader/modheader.crx");
ChromeOptions options = new ChromeOptions();
options.addExtensions(new File(currentRelativePath.toAbsolutePath().toString()));
ChromeDriver driver = new ChromeDriver(options);
driver.get("https://webdriver.modheader.com/add?test=ModHeader%20Test");
new WebDriverWait(driver, Duration.ofSeconds(500)).until(ExpectedConditions.titleIs("Done"));
```

using `chrome-extension://idgpnmonknjnojddfkpgkljpfnnfcklj/src/app_v1.html` i can inspect and automate that i don't need. instead of that using .crx directly add using from code i need to set. 

<img width="630" alt="Screenshot 2024-05-16 at 8 52 45 PM" src="https://github.com/modheader/modheader_selenium/assets/70950409/77ba92d2-440e-41c0-b823-f751169e4b1e">

**Comment by PRITHIVEE** [comment]
Hi @gowthaman99 

As per the docs, Please use this API to dynamically add headers after installation

`https://webdriver.modheader.com/add?{name1}={value1}&{name2}={value2}&...`

**Comment by iamgowthaman** [comment]
Thanks @PRITHIVEE , worked.
Closing the issue
